### ISSUE TITLE
crash on refresh

### ISSUE THREAD

**Issue by airforce270** [airforce270/airbot#217]
```
2023/09/12 18:19:13.248421 Failed to refresh helix auth token: failed to refresh token: (502: ) <nil>
2023/09/12 18:19:13.294889 Failed to refresh helix auth token: failed to refresh token: (502: ) <nil>
2023/09/12 18:19:13.465353 Failed to refresh helix auth token: failed to refresh token: (502: ) <nil>
2023/09/12 18:19:13.998995 Failed to refresh helix auth token: failed to refresh token: (502: ) <nil>
2023/09/12 18:19:14.741803 Failed to refresh helix auth token: failed to refresh token: (502: ) <nil>
2023/09/12 18:19:15.037740 Failed to refresh helix auth token: failed to refresh token: (502: ) <nil>
2023/09/12 18:19:15.984348 Failed to refresh helix auth token: failed to refresh token: (502: ) <nil>
2023/09/12 18:19:16.235055 Failed to refresh helix auth token: failed to refresh token: (502: ) <nil>
2023/09/12 18:19:16.599881 Failed to refresh helix auth token: failed to refresh token: (502: ) <nil>

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb9fd89]

goroutine 4047053 [running]:
github.com/nicklaw5/helix/v2.(*Client).refreshToken(0xc00007f540)
/go/pkg/mod/github.com/nicklaw5/helix/v2@v2.25.0/helix.go:430 +0x69
github.com/nicklaw5/helix/v2.(*Client).doRequest(0xc00007f540, 0xf22d64?, 0xc0020ee050)
/go/pkg/mod/github.com/nicklaw5/helix/v2@v2.25.0/helix.go:381 +0x275
github.com/nicklaw5/helix/v2.(*Client).sendRequest(0x7fb84e7b1a30?, {0xf22d64, 0x3}, {0xf28ff9, 0xe}, {0xd8f640, 0xc000262000}, {0xd8f600, 0xc0008aa000}, 0x0)
/go/pkg/mod/github.com/nicklaw5/helix/v2@v2.25.0/helix.go:182 +0xeb
github.com/nicklaw5/helix/v2.(*Client).get(...)
/go/pkg/mod/github.com/nicklaw5/helix/v2@v2.25.0/helix.go:144
github.com/nicklaw5/helix/v2.(*Client).GetChannelChatChatters(0xc0000a5300?, 0xc0008aa000)
/go/pkg/mod/github.com/nicklaw5/helix/v2@v2.25.0/chat.go:34 +0xa5
github.com/airforce270/airbot/platforms/twitch.(*Twitch).CurrentUsers(0xc000170780)
/go/src/github.com/airforce270/airbot/platforms/twitch/twitch.go:325 +0x1e6
github.com/airforce270/airbot/gamba.getInactiveUsers(0x0?, 0xc0006fd340?)
/go/src/github.com/airforce270/airbot/gamba/gamba.go:116 +0xe9
github.com/airforce270/airbot/gamba.grantPoints(0xc001f4bd00?, 0xc001e725a0?)
/go/src/github.com/airforce270/airbot/gamba/gamba.go:82 +0x2a
created by github.com/airforce270/airbot/gamba.StartGrantingPoints in goroutine 70
/go/src/github.com/airforce270/airbot/gamba/gamba.go:28 +0x27
```

**Comment by airforce270** [comment]
Fixed by https://github.com/nicklaw5/helix/pull/202
